[en]
  weight = 1
  # language code
  languageCode = "en"
  # language name
  languageName = "English"
  # whether to include Chinese/Japanese/Korean
  hasCJKLanguage = false
  # default amount of posts in each pages
  pagination.pagerSize = 12
  # copyright description used only for seo schema
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  # Menu config
  [en.menu]
    [[en.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Posts"
      url = "/posts/"
      # title will be shown when you hover on this menu link.
      title = ""
      weight = 1
    [[en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    # [[en.menu.main]]
    #   identifier = "categories"
    #   pre = ""
    #   post = ""
    #   name = "Categories"
    #   url = "/categories/"
    #   title = ""
    #   weight = 3
    # [[en.menu.main]]
    #   identifier = "series"
    #   pre = ""
    #   post = ""
    #   name = "Series"
    #   url = "/series/"
    #   title = ""
    #   weight = 4
    # [[en.menu.main]]
    #   identifier = "documentation"
    #   pre = ""
    #   post = ""
    #   name = "Docs"
    #   url = "/categories/documentation/"
    #   title = ""
    #   weight = 7
    [[en.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/me"
      title = ""
      weight = 3
    [[en.menu.main]]
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/morristai"
      title = "GitHub"
      weight = 4
  [en.params]
    # site description
    description = "The official documentation for the Hugo DoIt theme"
    # site keywords
    keywords = ["Rust", "Software", "Backend Development", "Distributed System"]
    # [UA-XXXXXXXX-X] google analytics code (replaced by params.analytics.google)
    googleAnalytics = "G-HSER3QLKLR"
    # App icon config
    [en.params.app]
      # optional site title override for the app when added to an iOS home screen or Android launcher
      title = "DoIt"
      # whether to omit favicon resource links
      noFavicon = false
      # modern SVG favicon to use in place of older style .png and .ico files
      svgFavicon = "/images/favicon.svg"
      # Safari mask icon color
      iconColor = "#5bbad5"
      # Windows v8-10 tile color
      tileColor = "#da532c"
    [en.params.search]  # TODO: Fix search
      enable = true
      # type of search engine ("lunr", "algolia", "fuse")
      type = "algolia"
      # max index length of the chunked content
      contentLength = 4000
      # placeholder of the search bar
      placeholder = ""
      # max number of results length
      maxResultLength = 10
      # snippet length of the result
      snippetLength = 300
      # HTML tag name of the highlight part in results
      highlightTag = "em"
      # whether to use the absolute URL based on the baseURL in search index
      absoluteURL = false
      [en.params.search.algolia]
        index = "en_index"
        appID = "R7I3523JS6"
        searchKey = "5cd3256ef82c1bd37aab2e4573b2f0ad"
    # Home page config
    [en.params.home]
      # amount of RSS pages
      rss = 10
      # Home page profile
      [en.params.home.profile]
        enable = true
        # Gravatar Email for preferred avatar in home page
        gravatarEmail = ""
        # URL of avatar shown in home page
        avatarURL = "/images/avatar.jpg"
        # title shown in home page (HTML format is supported)
        title = ""
        # subtitle shown in home page
        subtitle = "\"There is only one heroism in the world: to see the world as it is, and to love it.\" - Romain Rolland"
        # whether to use typeit animation for subtitle
        typeit = false
        # whether to show social links
        social = true
        # disclaimer (HTML format is supported)
        disclaimer = ""
      # Home page posts
      [en.params.home.posts]
        enable = true
        # special amount of posts in each home posts page
        paginate = 5
    [en.params.author]
      name = "Morris"
      email = "morristai01@gmail.com"
      link = "https://github.com/morristai"
      avatar = "/images/avator_icon.png"
    # Social config in home page
    [en.params.social]
      GitHub = "morristai"
      Twitter = "morristai01"
      Instagram = "morristai01"
      Linkedin = "morris-tai-509306118"
      Email = "morristai01@gmail.com"
      RSS = true
      [en.params.social.Mastodon]
        id = "@morristai"
        prefix = "https://hachyderm.io/"
[zh-tw]
  weight = 2
  languageCode = "zh-TW"
  languageName = "繁體中文"
  hasCJKLanguage = true
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  [zh-tw.menu]
    [[zh-tw.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      name = "所有文章"
      url = "/posts/"
      # title will be shown when you hover on this menu link.
      # 将鼠标悬停在此菜单链接上时将显示标题。
      title = ""
      weight = 1
    [[zh-tw.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "關於"
      url = "/about/me"
      title = ""
      weight = 8
    [[zh-tw.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "標籤"
      url = "/tags/"
      title = ""
      weight = 2
    [[zh-tw.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分類"
      url = "/categories/"
      title = ""
      weight = 3
    [[zh-tw.menu.main]]
      identifier = "series"
      pre = ""
      post = ""
      name = "系列"
      url = "/series/"
      title = ""
      weight = 4
