baseURL = 'https://morristai.github.io'
languageCode = 'en-us'
title = "Morris.Blog"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  comments = true
  [params.gitalk]
    owner = "morristai" # GitHub ID
    repo = "morristai.github.io.comments"
    clientId = "c39ea41a62ca2985fa6a"
    clientSecret = "ce5b1903b1ea9eb8bbb83f363d44935965b155f1"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.taxonomies]
      category = "categories"
      tag = "tags"
      series = "series"
    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "Archive"
        url = "archives"
        weight = 5

      [[languages.en.menu.main]]
        name = "Search"
        url = "search/"
        weight = 10

      [[languages.en.menu.main]]
        name = "Tags"
        url = "tags/"
        weight = 10
      [[languages.en.menu.main]]
        name = "Resume"
        url = "/docs/resume_morris_tai.pdf"
        weight = 10

    #   [[languages.en.menu.main]]
    #     name = "WiKi"
    #     url = "https://github.com/adityatelange/hugo-PaperMod/wiki/"

    #   [[languages.en.menu.main]]
    #     name = "Discord"
    #     url = "https://discord.gg/ahpmTvhVmp"
 